### ISSUE TITLE
DaccredBase.sol

### ISSUE THREAD

**Issue by koolamusic** [daccred/contracts#12]
This would be the core implementation of a daccred. 

`DaccredBase.sol`  is an ERC-721 token that adopts some key structures from `ERC721A` 
Once we have this, we will then need another Factory that can create child `Core` contracts. will document the specs for that in another issue. 

However the scope of this issue is an NFT contract that supposed the full specification of the ERC-721 but is gas optimized and cost very little to mint like the implementation https://github.com/chiru-labs/ERC721A

**Comment by koolamusic** [comment]
@fps8k renaming this to `DaccredBase` as it's more appropriate. base is the standard implementation of a daccred

**Comment by 0xfps** [comment]
Ok.

**Comment by 0xfps** [comment]
It's all coming together 😊😊.

**Comment by koolamusic** [comment]
I await your PR 😄

**Comment by 0xfps** [comment]
The DaccredBase contract is done. I am about to commence review and testing 😊.

**Comment by koolamusic** [comment]
nice. well done 👏🏾
