### ISSUE TITLE
`DaccredDeployer.sol`

### ISSUE THREAD

**Issue by koolamusic** [daccred/contracts#13]
This contract has only one job compose all the extension contracts and expose them as functions that take in an argument, see this https://github.com/Uniswap/v3-core/blob/8f3e4645a08850d2335ead3d1a8d0c64fa44f222/contracts/UniswapV3PoolDeployer.sol#L27

### Caveats
Handling contract parameters. every child contract composed with an extension cannot have the same constructor argument. so it will be crucial to understand how to design this. 

A known way would be to trigger a function call directly to the function that creates a particular type of extension. example

```js
import "CoreSoulboundWhitelist.sol"
import "SoulboundWhitelistPaidExtension.sol"

contract DaccredDeployer {

enum Extension {
    CoreSoulboundWhitelist,
    SoulboundWhitelistPaidExtension
}
event ContractDeployedEvent(..., Extension type)
struct CallData {...}

function deployCoreSoulbound(cd CallData) external 

function deploySoulboundWhitelistPaidExtension(cd CallData) external

}
```

The above pseudo code is an idea of how the deployer should work. however notice how `CallData` is one struct, in principle it might be hard to use one struct to define all the constructor arguments for each extension, so it will be wise to create a new type for each functionWithExtension. 

Also the purpose of the `enum` is to track which contracts are gettting published the most, ofc we can also emit `address, deployer` etc as part of the event. 

Using `CREATE2` we can read addresses before hand. 

With these individual functions, the client apps can call the function directly without interacting with any mediator in the contract.

**Comment by koolamusic** [comment]
An update to this issue. The enum is irrelevant as we just use the functions to directly deploy a type of template

**Comment by koolamusic** [comment]
> DEPLOYER VARIABLES
We can embelish the deployer with certain default variables to use in constructor arguments for child contracts. example

- `DEFAULT_SUPPLY = 1_000_000` here we default the supply of a token to a million individuals so we can limit mints to capped supply
- `DEFAULT_EXPIRY_DATE = now + 100 years` a situation where we want a token to expire, but the user does not supply any arguments

**Comment by koolamusic** [comment]
Deployer Extensions
- Pausable
- Ownable
- Non Re-Entrant

**Comment by 0xfps** [comment]
Re-Entrant?

**Comment by koolamusic** [comment]
fixed it, lol
