### ISSUE TITLE
`SoulboundCore.sol` Template

### ISSUE THREAD

**Issue by koolamusic** [daccred/contracts#16]
This template will have the following extensions

- Soulbound EIP
- Ownable
- With Signature to enable revoke and issue

**Comment by 0xfps** [comment]
Will the Allowlist be used here?

**Comment by koolamusic** [comment]
yes. 
Since allowlist is an implementation of with signature. let's add it to all templates by default and use a toggle to enable it

**Comment by 0xfps** [comment]
Ok.
