### ISSUE TITLE
`SoulboundWithSignature` Template

### ISSUE THREAD

**Issue by koolamusic** [daccred/contracts#17]
This template will have the following extensions

- Soulbound EIP
- Ownable
- With Signature to enable revoke and issue
- Capped Supply 

The difference between this and the core implementation is that it gives power to the owner (deployer) of the contract to perform actions like 

- revokeWithSignature
- issueWithSignature

**Comment by 0xfps** [comment]
Is the capped supply set by us, or the deployer's choice?
If it is set by us, what value do we set?

**Comment by koolamusic** [comment]
deployer choice, however when it is not supplied to the contract, we default to 1 million
