### ISSUE TITLE
Soulbound Extension

### ISSUE THREAD

**Issue by koolamusic** [daccred/contracts#2]
Create an option to disable transfer of NFTs minted on the platform. So they can be soulbound.

This will make the token in-compatible with the NFT spec, but also achieves the purpose of soulbound. 

Another way would be to have a transfer mechanism that is disabled and can only be approved by owner or deployer of said NFT

**Comment by koolamusic** [comment]
Soulbound is a very experimental extension and we would try to highlight it in the client section. 
There have been a lot of proposals 
1. https://ethereum-magicians.org/t/eip-5114-soulbound-badges/9417
2. 



However among these proposals, the one with the least friction to adoption and compatible interface is https://github.com/TimDaub/EIPs/blob/194f91067b8ef843467c15821ca5a5e3aa129fe6/EIPS/eip-4973.md

You can find the Pull Request with sample code here https://github.com/ethereum/EIPs/pull/4973/files#diff-78eda02f8170e73250f20c44a63a94888296116f3fec90171d5e766ce312f5af

```sol
  /// authenticated `from` field.
  event Attest(address indexed _to, uint256 indexed _tokenId);
  /// @dev This emits when an existing ABT is revoked from an account and
  /// destroyed by any mechanism.
  /// Note: For a reliable `_from` parameter, retrieve the transaction's
  /// authenticated `from` field.
  event Revoke(address indexed _to, uint256 indexed _tokenId);
  /// @notice Find the address bound to an ERC4973 account-bound token
  /// @dev ABTs assigned to zero address are considered invalid, and queries
  ///  about them do throw.
  /// @param _tokenId The identifier for an ABT
  /// @return The address of the owner bound to the ABT
  function ownerOf(uint256 _tokenId) external view returns (address);
```

It provides an interface that's lean enough to cater to the needs of irrevocable account tokens

**Comment by koolamusic** [comment]
Some remarkable examples
https://github.com/marryinweb3/ERC721-520
https://marry3.love/
https://ethereum-magicians.org/t/eip-4671-non-tradable-token/7976
https://ethereum-magicians.org/t/eip-4671-non-tradable-token/7976/2

**Comment by 0xfps** [comment]
The interface has been long done. I will add the comments.
