### ISSUE TITLE
Payable Mint Extension

### ISSUE THREAD

**Issue by koolamusic** [daccred/contracts#5]
This Extension enable users to charge for `mints` in the Native token of the Network where the token is being issued.

For example
- ONE in Harmony Network
- MATIC in polygon
- ETH in Ethereum etc.

**Comment by NatX223** [comment]
If the user is not the one paying in the native token, then it would best to handle it from an API/backend.

**Comment by koolamusic** [comment]
For payable mints, the users pay to mint

**Comment by koolamusic** [comment]
Withdrawal function.

We will maintain a MULTI-SIG DEV WALLET ADDRESS.
such that whenever users want to withdraw funds from a payable credentials, 

We also get paid as well. the markup can be 10% for free accounts

**Comment by 0xfps** [comment]
I'll look into and do that.
