### ISSUE TITLE
AllowList Module

### ISSUE THREAD

**Issue by koolamusic** [daccred/contracts#6]
Whitelist or Allowlists are popular gating mechanisms when minting NFTs. As much as we implement a version of this on the product level, we also need one that works on the contract level and the shortlists are 

#### Merkle Trees
Some resources
https://medium.com/donkeverse/hardcore-gas-savings-in-nft-minting-part-2-signatures-vs-merkle-trees-917c43c59b07

#### ECRecover implementation
https://soliditydeveloper.com/ecrecoverhttps://flyingnobita.com/posts/2022/05/07/mint-nft-ecdsa
https://flyingnobita.com/posts/2022/05/07/mint-nft-ecdsa

- https://betterprogramming.pub/handling-nft-presale-allow-lists-off-chain-47a3eb466e44 [QUITE SUBJECTIVE]

We can implement private key per accounts on the API to support either ECDSA or Merkle Proof implementations smart contract wise. A really good read below
> https://nftchance.medium.com/the-gas-efficient-way-of-building-and-launching-an-erc721-nft-project-for-2022-b3b1dac5f2e1

**Comment by koolamusic** [comment]
https://github.com/miguelmota/merkletreejs-solidity

**Comment by 0xfps** [comment]
I think the best option here is to use ECDSA for signing and verifying signatures.
